// _shared/modules-26-32.ts
// Modules 26-32 — Track F: Rejection & Resilience.
// Coaching layer Phase 5b (admin/coaching-layer-design.md v1.10 §4.4).
// Generated 2026-05-18.
//
// Track F covers the psychological topics no career book covers properly:
// the moments where most independents quit (silence, explicit rejection,
// imposter spikes, week-three doubt, the "just take a job" pull, peer
// comparison anxiety, the family conversation). Each module follows the
// same shape as the existing 25, with a tighter question set (2-3 questions)
// because these topics personalise from light context rather than the
// 5-question operational shape Tracks A-D use.
//
// Voice: warmer than Tracks A-D on this topic class, but the contract still
// holds — no abstract reassurance, no em-dashes, no banned words, no
// motivational language. Direct, specific, older-sibling. The lesson the
// LLM generates from each output_structure must name the friction precisely
// and give one concrete next move, never platitudes.

import type { RichModule } from "./modules-rich-types.ts";

export const MODULES_26_32: Record<number, RichModule> = {
  26: {"id":26,"name":"Handling silence after sending","track":"F","access_tier":"subscription","applicable_sectors":null,"prerequisite_module":null,"area":"Resilience","trigger_phase":"Triggered when a sent move stays silent past 5 days","estimated_minutes":4,"output_type":"silence_response","description":"The most common moment people quit. What silence usually means, and the specific next move when a sent message doesn't come back.","questions":[{"id":"sent_recency","text":"How many days has it been since you sent the message you're thinking about?","type":"choice","options":["1-3 days","4-7 days","8-14 days","Over two weeks"]},{"id":"sent_relationship","text":"Was this a cold contact, a warm reconnect, or a referral introduction?","type":"choice","options":["Cold (no prior contact)","Warm reconnect (someone I used to know)","Referral introduction (someone introduced us)","Existing contact I had not spoken to in a while"]},{"id":"usual_response_time","text":"In your experience, how quickly do people in your network normally reply to non-urgent professional messages?","type":"choice","options":["Within 24 hours typically","Within a few days","A week is normal","Highly variable, often longer"]}],"output_structure":{"what_silence_usually_means":"1-2 sentences naming what silence at this day-count and relationship type usually indicates. Calm, factual. Not 'they hate you'. Not 'they're definitely busy'. The honest distribution.","what_to_do_now":"ONE specific next move based on day-count and relationship. Cold + day 3 = wait, cold + day 7 = single-line follow-up, warm + day 5 = ask if you missed a reply, etc. Concrete and observable, no frameworks.","what_not_to_do":"The 2-3 common mistakes at this moment: not the long apologetic follow-up, not the second cold push within the same week, not the assumption that silence means a definitive no.","longer_view":"One sentence on the portfolio framing. The individual move is cheap; the portfolio works because each move is cheap. Reframes the silence as data, not failure.","caveat":"This is general guidance based on the typical pattern of professional outreach. The specifics of your relationship and context override the defaults here."}},

  27: {"id":27,"name":"Handling explicit rejection","track":"F","access_tier":"subscription","applicable_sectors":null,"prerequisite_module":null,"area":"Resilience","trigger_phase":"Triggered when a contact explicitly declines","estimated_minutes":4,"output_type":"rejection_response","description":"When someone says no directly. How to separate the no from the relationship, what to do in the next 48 hours, and the move most people miss.","questions":[{"id":"rejection_type","text":"What kind of no was it?","type":"choice","options":["A clear no with no reason","A soft no (\"not right now\", \"maybe later\")","A no with a specific reason","A redirect (\"not me, try X\")"]},{"id":"relationship_status","text":"Do you want this relationship to continue beyond this engagement?","type":"choice","options":["Yes, it's a long-term contact worth preserving","Yes, but it was transactional","No, this was a one-off","Unsure"]},{"id":"emotional_weight","text":"How much is this one weighing on you right now?","type":"choice","options":["Lightly, it stings but it's fine","Moderately, it's on my mind","Significantly, it's affecting the rest of my week"]}],"output_structure":{"what_the_no_actually_means":"1-2 sentences reading the no honestly. A soft no often is a no. A redirect is often a gift. A reason-given no usually contains information worth using. Match the read to the type from the input.","the_48_hour_move":"ONE specific action to take in the next two days. The standard move: a short, gracious reply that acknowledges + asks one clarifying question (if a reason was given) or thanks them and closes the loop (if it was a clear no).","relationship_preservation":"The often-missed follow-up that keeps the door open without being awkward. The specific message to send 8-12 weeks from now if relationship_status says continue, including what to anchor it to.","longer_view":"One sentence on what this no buys you. The honest version: a clear no removes a maybe from your pipeline, which is more useful than a polite delay.","caveat":"When emotional weight is significant, the next move can wait 24 hours. The reply you draft tomorrow morning will almost always be better than the one you draft tonight."}},

  28: {"id":28,"name":"Handling the imposter spike after a small win","track":"F","access_tier":"subscription","applicable_sectors":null,"prerequisite_module":null,"area":"Resilience","trigger_phase":"Triggered after first reply / first paid hour / first explicit interest","estimated_minutes":4,"output_type":"imposter_reframe","description":"The strange thing that happens after the first reply, the first paid hour, the first introduction landing. Why the imposter voice gets louder right when things start working, and the specific move to make next.","questions":[{"id":"win_type","text":"What was the small win?","type":"choice","options":["First reply to outreach","First paid work or first invoice","First meaningful introduction landing","First explicit expression of interest","Something else"]},{"id":"imposter_voice","text":"In one line, what is the imposter voice currently saying? (Optional, leave blank if you'd rather not articulate it.)","type":"text","optional":true,"placeholder":"e.g. \"They'll realise I'm out of my depth.\""}],"output_structure":{"why_this_spike_happens":"1-2 sentences naming the pattern. Imposter peaks at the moment the abstract becomes real, not when things go wrong. Use the specific win type from the input.","the_specific_thought_to_replace":"The cognitive move. If they shared an imposter line in Q2, address it directly. Otherwise: name the typical replacement thought ('this is the data point I was working for' rather than 'they'll realise I'm out of my depth').","the_next_action":"ONE small observable action in the next 24 hours that takes the win seriously without overcorrecting into either grandiosity or self-doubt. Often: log it somewhere, name the next move in the same direction, do not pivot the strategy on a single data point.","longer_view":"One sentence on what this spike means about your trajectory. The honest version: this discomfort tracks closely with the work starting to land. People who never feel this often are not pushing hard enough.","caveat":"If the imposter voice is consistently loud across multiple wins over months, that's a different signal worth talking to a coach or therapist about. This module addresses the in-the-moment spike, not chronic patterns."}},

  29: {"id":29,"name":"Handling the doubt at week three","track":"F","access_tier":"subscription","applicable_sectors":null,"prerequisite_module":null,"area":"Resilience","trigger_phase":"Triggered around days 18-24 of the activation plan","estimated_minutes":4,"output_type":"week_three_reframe","description":"The structural moment when momentum dips. What week three usually is, why most people misread it as failure, and the specific re-engagement move that gets the trajectory back.","questions":[{"id":"current_state","text":"Where are you in the dip?","type":"choice","options":["Just hit it, things suddenly feel hard","Mid-week, in the middle of it","Coming out, but not sure if I'm back yet"]},{"id":"dominant_friction","text":"What is your current dominant friction? (Optional)","type":"text","optional":true,"placeholder":"e.g. \"I've sent messages and heard nothing back\""}],"output_structure":{"what_week_three_usually_is":"1-2 sentences naming the structural pattern. The initial momentum carries you through weeks one and two; week three is when the first wave of replies (or non-replies) lands and the abstract becomes specific. The dip is the system working, not breaking.","the_specific_reframe":"Name the typical misread (\"it's not working\") and the actual read (\"it's working at the typical rate, which is slower than the activation high suggested\"). If they shared a friction in Q2, address it directly.","the_re_engagement_move":"ONE concrete thing for the next 72 hours. The most common right move: pick the single most overdue task in the plan and do the smallest possible version of it. Specific to their current_state from Q1.","longer_view":"One sentence on what week three breaks. The honest version: most people who quit quit here. People who make it to week four usually break through in weeks five to seven.","caveat":"If the dip extends past week four with no movement, that's the moment to look at the plan structure rather than push through harder. The Replan affordance exists for exactly this signal."}},

  30: {"id":30,"name":"Handling the \"should I just take a job\" moment","track":"F","access_tier":"subscription","applicable_sectors":null,"prerequisite_module":null,"area":"Resilience","trigger_phase":"Triggered when the safe option starts to look attractive again","estimated_minutes":5,"output_type":"job_pull_decision","description":"When the safe option starts to look attractive again. What's actually happening, what's worth pausing the plan for vs. not, and the specific decision framework before you act.","questions":[{"id":"trigger","text":"What surfaced this thought today?","type":"choice","options":["A slow week with no replies","A specific job opportunity that landed","Financial pressure","A family conversation","General doubt without a specific trigger"]},{"id":"financial_runway","text":"How much runway do you have at your current burn rate?","type":"choice","options":["Less than 3 months","3-6 months","6-12 months","Over 12 months","I don't track this precisely"]},{"id":"opportunity_specifics","text":"Is there a specific job on the table right now?","type":"choice","options":["Yes, a concrete offer","Yes, an early conversation","No, this is hypothetical"]}],"output_structure":{"whether_this_is_signal_or_noise":"The read. A slow week + 12 months runway = noise. A concrete offer + sub-3-month runway = signal. Match the read to the inputs from Q1, Q2, Q3 specifically.","the_decision_framework":"Three questions to answer in writing before any move. Examples: (1) If I take this job, what's the smallest version of independent work I keep alive in parallel? (2) Is the runway pressure real or is the work pressure real? (3) What would the version of me writing this in three months hope I did?","what_pausing_actually_costs":"The honest version of what pausing the plan now costs vs. what taking the job buys. Includes: 30 days in is roughly halfway to first revenue for most paths; six months of salaried work resets the activation runway, not the strategy.","longer_view":"One sentence reframing the choice. The honest version: taking a job is often the right move and is not failure. Pausing the plan badly is failure. There is a way to do this that preserves the option.","caveat":"This module is decision support, not advice. A real financial cliff or a meaningful job offer always deserves a conversation with someone who knows your specific situation. Use this to think clearly, then talk to a person."}},

  31: {"id":31,"name":"Handling comparison anxiety when a peer announces something good","track":"F","access_tier":"subscription","applicable_sectors":null,"prerequisite_module":null,"area":"Resilience","trigger_phase":"Triggered by a peer's public announcement that lands hard","estimated_minutes":4,"output_type":"comparison_response","description":"The specific psychological move when someone in your network posts a win that lands harder than you expected. Why it happens, what the spike tells you, and the response that actually helps your work.","questions":[{"id":"peer_proximity","text":"Was this peer in a path close to yours, or a different one entirely?","type":"choice","options":["Very close (similar archetype, similar stage)","Somewhat adjacent (similar industry, different path)","Different path entirely (a friend or former colleague in a different field)"]},{"id":"announcement_type","text":"What did they announce?","type":"choice","options":["A new job or promotion","A client win or new engagement","A book, podcast, or public visibility","A company milestone (sale, raise, exit)","General visibility (a popular post, a press mention)"]},{"id":"response_so_far","text":"What have you done in the hour since seeing it? (Optional)","type":"text","optional":true,"placeholder":"e.g. \"Closed the tab and felt deflated for the rest of the morning\""}],"output_structure":{"what_the_spike_tells_you":"The useful signal in the discomfort. A spike that lands hard usually points at something specific you want for yourself. Close-peer + similar-stage spikes are more useful than far-peer spikes because the proximity sharpens the signal. Use the proximity from Q1.","the_specific_response":"What to send the peer in the next 24 hours. A short, specific reply (\"the bit about X landed for me\") is more relationship-building than silence and more honest than performative enthusiasm. Match to the announcement_type from Q2.","the_self_directed_move":"What to do for your own work in the next 48 hours. The most common right move: write down the specific thing the announcement made you want, and the smallest move toward it you could make this week. Concrete, observable, single.","longer_view":"One sentence reframing what comparison does. The honest version: in a portfolio of moves, your peers' wins are also data points about what's possible. Used well, they update your model. Used badly, they shrink it.","caveat":"If the comparison spike is consistent across many peers over months, that's a different pattern worth looking at separately. This module is about the in-the-moment response, not the chronic loop."}},

  32: {"id":32,"name":"Handling the partner or family conversation","track":"F","access_tier":"subscription","applicable_sectors":null,"prerequisite_module":null,"area":"Resilience","trigger_phase":"Triggered when the conversation is overdue or has gone badly","estimated_minutes":5,"output_type":"family_conversation_framework","description":"The conversation that often determines whether your plan survives the next 90 days. What to share, what not to share, and the specific structure that works for both sides.","questions":[{"id":"conversation_status","text":"Have you had this conversation in any meaningful form yet?","type":"choice","options":["No, I've been avoiding it","Partial, I've mentioned things but not had a real conversation","Yes, recently, and it did not go well","Yes, recently, and it went okay but feels unresolved"]},{"id":"their_concern","text":"What is their primary concern?","type":"choice","options":["Income and financial security","Your wellbeing and stress","Specific timing (e.g. a family event coming up)","General risk and the unknown","I'm not sure what their primary concern is"]},{"id":"relationship_dynamic","text":"How do the two of you typically have hard conversations?","type":"choice","options":["Head-on, we both prefer directness","Over time, in small pieces","With structure (we plan and schedule them)","With some avoidance, they tend to drift"]}],"output_structure":{"what_to_share":"The specific framing of your plan that addresses their actual concern from Q2. Includes: the timeline you're working to, the financial picture (specific numbers, not vague reassurance), the signals that will tell both of you whether it's working, and what you would do if those signals don't show up.","what_not_to_share":"The over-share that makes it worse. Includes: every fluctuation in your daily mood, every speculative opportunity that hasn't landed yet, the imposter voice in real-time. Their job is not to absorb your day-to-day variance.","the_structure_that_works":"A specific way to have the conversation matched to their relationship_dynamic from Q3. For 'head-on': one focused sitting, clear ask at the start. For 'over time': three short conversations rather than one long one. For 'with structure': a written one-pager to read before talking. For 'with avoidance': a specific scheduled time with a soft anchor (a meal, a walk).","the_next_check_in":"What to agree on for follow-up. Specific cadence (e.g. monthly), specific signals to review (e.g. pipeline conversations, savings runway), and a pre-agreed trigger that prompts a bigger conversation (e.g. \"if we hit 4 months of runway with no revenue\").","caveat":"This is structure for a specific kind of working conversation. It is not a substitute for the deeper relationship conversations that may also need to happen. If the underlying dynamic is strained beyond the plan itself, that's a different piece of work."}},
};
