// _shared/modules-1-9.ts
// Modules 1-9 from canonical guidance_modules.json v2.0
// Generated 2026-05-15. Imported by modules-library-rich.ts.

import type { RichModule } from "./modules-rich-types.ts";

export const MODULES_1_9: Record<number, RichModule> = {
  1: {"id":1,"name":"Business Structure","track":"A","access_tier":"tranche_1","applicable_sectors":null,"prerequisite_module":null,"area":"Legal & Tax Foundation","trigger_phase":"Days 1–7","estimated_minutes":5,"output_type":"decision_with_rationale","description":"Sole trader, limited company, or umbrella — the foundational decision everything downstream depends on.","what_you_get":"A clear structure recommendation with rationale, the key setup steps, and what to do first.","questions":[{"id":"expected_income_year1","text":"What is your expected annual income in Year 1 from independent work?","type":"choice","options":["Under £30,000","£30,000–£50,000","£50,000–£80,000","Over £80,000","Unsure — too early to say"]},{"id":"work_pattern","text":"Will most of your work be on fixed-term contracts for a single client, or spread across multiple clients on projects and advisory work?","type":"choice","options":["Primarily one client at a time on fixed contracts","Multiple clients, project or advisory basis","Mix of both","Not sure yet"]},{"id":"client_ltd_requirement","text":"Do your target clients typically require you to operate as a limited company to engage you?","type":"choice","options":["Yes, most require a Ltd","No, sole trader is fine","Unsure"]},{"id":"admin_appetite","text":"How comfortable are you with annual admin — filing accounts, corporation tax returns, director responsibilities?","type":"choice","options":["Fine with it — I can handle complexity","I prefer simplicity where possible","Not sure what's involved yet"]},{"id":"liability_concern","text":"Are you concerned about personal liability for the work you do?","type":"choice","options":["Not really — my work carries low personal risk","Somewhat concerned","Yes — my work carries meaningful professional risk"]}],"decision_logic":{"sole_trader_signals":["Under £30k income","multiple clients advisory basis","no client Ltd requirement","prefers simplicity"],"ltd_signals":["Over £50k income","client requires Ltd","high professional liability","admin comfortable"],"umbrella_signals":["single client fixed contracts","IR35 uncertainty","income under threshold","wants simplicity while testing market"],"notes":"Ltd tax efficiency only kicks in above ~£30-35k profit. Single dominant client + Ltd = higher IR35 risk."},"output_structure":{"recommendation":"sole_trader | limited_company | umbrella","rationale":"3-4 specific reasons tied to their answers","key_considerations":"Any material caveats or deciding factors","next_steps":"2-3 immediate actions","caveat":"This is a structured decision framework, not professional tax advice. If your situation is complex — particularly around IR35 or significant income — confirm with an accountant. Many offer a one-off consultation for around £150–200."},
    module_addendum: {
      module_decision_frame: "Decision between three structures: sole_trader (light-touch default), limited_company (separate legal entity, own tax regime), and umbrella (employed status via intermediary for single-client inside-IR35 work). Recommend exactly one structure. Anchor the recommendation to the user's specific Q1 (income range), Q2 (work pattern), Q3 (client Ltd requirement), Q4 (admin appetite), and Q5 (liability concern). Revisit triggers: £60,000 consistent profit, FS or public-sector client Ltd requirement, change in IR35 exposure.",
      module_specific_knowledge: `Sole trader fits when income is variable or below £60,000 consistent profit, work is across multiple clients, and the user wants minimal administrative burden. Tax structure: Income Tax + Class 2 NI (~£3.45/week above threshold) + Class 4 NI (9% from £12,570 to £50,270; 2% above) on trading profits. Personal Allowance of £12,570 applies to total income. No corporation tax. No Companies House filings. Records kept for 5 years past the 31 January filing deadline. Self Assessment registration trigger: the first paid piece of work. Late registration after 5 October following the tax year carries a £100 starting penalty.

Limited company fits when income is reliably above £60,000 (the tax advantage emerges as dividends are taken above the £37,700 dividend basic-rate band and into the higher rate, where corporation tax + dividend tax remains lower than personal income tax + NI), when the user wants liability separation, or when a client requires it. The trade-off is real admin overhead: separate corporation tax return, annual accounts filed with Companies House, separate director self-assessment, quarterly VAT if registered. Setup costs around £12 for incorporation. Annual accountancy costs typically £600-£1,500 for a small Ltd.

Umbrella fits a narrow case: a single inside-IR35 engagement where the client requires it, the user has no appetite for company admin, and they want PAYE simplicity. The umbrella becomes the legal employer; the user is an employee paid PAYE; the umbrella deducts a margin (typically £15-£30/week) and pays employer's NI from the gross. Net pay is lower than sole trader or Ltd-outside-IR35 because employer's NI comes out of the rate envelope. Umbrella is almost never the right answer for advisory or outside-IR35 work.

IR35 (off-payroll working rules) matters mainly for limited company users: it determines whether HMRC treats a Ltd contract as "disguised employment", in which case the Ltd's tax advantage evaporates and PAYE-equivalent tax applies. For inside-IR35 engagements through a Ltd, the user takes the same hit as PAYE; the Ltd's value is preserved only for outside-IR35 work. Public sector clients determine IR35 status; private sector medium-large clients also determine; small private clients (the user determines).

Switching paths: sole trader to limited company is straightforward (form a new Ltd, transition the trade, declare cessation of sole trader). Limited company to sole trader is harder (close the company via strike-off or members' voluntary liquidation, which has tax implications). Plan to be in the chosen structure for at least 2 years before reviewing.

Common misconceptions to dispel where relevant: (1) "Ltd companies sound more professional" — clients care about contracts, deliverables, and PI insurance, not legal structure. (2) "Ltd companies pay less tax" — true above £60k of consistent profits with dividend extraction strategy; not at £30-50k. (3) "I'll get personal liability protection from going Ltd" — true for company debts; not for personal negligence claims, which is what PI insurance covers. (4) "I should incorporate before I start trading" — no; trading status is determined by activity, not registration.`,
      curated_caveat_base: "Tax thresholds, deadlines, and broker recommendations above were verified [DATE]. Always confirm current rules at gov.uk and hmrc.gov.uk before acting.",
      curated_caveat_verified_date: "2026-05-25",
      commitments_template: [
        { action_hint: "Start Self Assessment registration", target_day: 5, verification_question: "Have you started the HMRC Self Assessment registration?" },
        { action_hint: "Contact a PI insurance broker", target_day: 7, verification_question: "Have you contacted a professional indemnity broker?" },
        { action_hint: "Set up a tax savings account", target_day: 7, verification_question: "Have you set up a separate account for tax reserves?" },
      ],
      prerequisite_outputs: null,
    },
  },
  2: {"id":2,"name":"Registration & Setup","track":"A","access_tier":"tranche_1","applicable_sectors":null,"prerequisite_module":1,"area":"Legal & Tax Foundation","trigger_phase":"After Module 1","estimated_minutes":5,"output_type":"sequenced_checklist","description":"Exactly what to register, in what order, with timeframes — tailored to your chosen structure.","what_you_get":"A step-by-step registration checklist with exact actions, timeframes, and costs.","questions":[{"id":"trading_started","text":"Have you already started doing any paid independent work?","type":"choice","options":["No, not yet","Yes, a small amount — under a few hundred pounds","Yes, I've been doing this regularly"]},{"id":"business_bank_account","text":"Do you already have a dedicated business bank account?","type":"choice","options":["Yes","No — using personal account","No — haven't set one up yet"]}],"output_structure":{"checklist_items":"Sequenced registration steps for their structure (sole_trader | limited_company | umbrella)","ico_registration":"Required / Likely required / Not required — based on Q4 work type and Q11 sector","priority_flags":"Any items flagged as urgent given their trading status","caveat":"Registration deadlines and requirements can change. Always verify current rules at gov.uk and hmrc.gov.uk."},"ico_logic":{"required":["data analysis involving personal data","HR advisory","recruitment","healthcare","financial advice involving personal records"],"likely_required":["consulting with access to client employee/customer data","project delivery involving personal data systems"],"not_required":["purely analytical work on anonymised data","strategic advisory with no personal data access"]},
    module_addendum: {
      module_decision_frame: "User chose a structure in Module 1 (sole trader, limited company, or umbrella) and now needs the exact registration sequence with timeframes and costs. Produce a sequenced checklist tailored to the chosen structure plus an ICO registration determination based on Q4 work type and Q11 sector from the main questionnaire. Anchor urgency to Q1 trading_started: if the user has already done paid work, the HMRC Self Assessment clock is already running and registration is overdue rather than upcoming.",
      module_specific_knowledge: `Sole trader registration: complete at gov.uk/register-for-self-assessment using your National Insurance number. Takes about 15 minutes. HMRC posts a UTR (Unique Taxpayer Reference) within 10 working days. Registration deadline is 5 October following the tax year in which the first paid piece of work occurred. The initial late-registration penalty is £100 and rises with continued delay. No fee to register.

Limited company registration: incorporate at Companies House (find-and-update.company-information.service.gov.uk) for a £50 online fee. The incorporation completes within 24 hours typically. Corporation Tax registration is triggered automatically post-incorporation; HMRC sends an activation letter to the registered office within 14 days. Set up PAYE before paying yourself a salary (gov.uk/register-employer); even sole-director companies need PAYE if drawing salary above the Lower Earnings Limit. Annual filings are: company accounts due 9 months after year-end, confirmation statement annually (£34), corporation tax return CT600 12 months after year-end (payment 9 months and 1 day after).

Umbrella company onboarding: select an umbrella accredited by FCSA or Professional Passport (these are the two recognised industry bodies). Onboarding takes 1-3 days: right-to-work check, contract issuance, P45 transfer if applicable. Read the Key Information Document (KID) before signing, it discloses the umbrella margin, statutory deductions, and net take-home illustration. Umbrella margins vary £15-£35 per week typically.

ICO registration: legally required for any data controller processing personal data in the course of business under the Data Protection (Charges and Information) Regulations 2018. Fees: £40 (tier 1, micro), £60 (tier 2, SME), or £2,900 (tier 3, large), most independents fall in tier 1 or 2. Register at ico.org.uk/registration in about 10 minutes. Renewal is annual.

Business bank account: legally required for a limited company (the company is a separate legal entity and must not commingle funds). Strongly recommended for sole trader for clean records and audit trail. Traditional banks (HSBC, Barclays, Lloyds) take 2-4 weeks and may require an in-branch appointment. Neobanks (Starling, Tide, Monzo Business, Revolut Business) onboard within 1-3 days, often same-day. Starling and Tide are particularly common among independent consultants.

VAT and PAYE registrations are separate and triggered only when applicable (see Module 5 for VAT, Module 7 employer setup for PAYE).`,
      curated_caveat_base: "Registration deadlines, fees, and exact procedural steps occasionally change at Budget or Autumn Statement. Verify each step at gov.uk, companies-house.gov.uk, and ico.org.uk before acting. Verified [DATE].",
      curated_caveat_verified_date: "2026-05-25",
      commitments_template: [
        { action_hint: "Complete primary structure registration", target_day: 3, verification_question: "Have you registered with HMRC or Companies House for your chosen structure?" },
        { action_hint: "Register with ICO if applicable", target_day: 7, verification_question: "Have you registered with the ICO, or confirmed registration is not required for your work?" },
        { action_hint: "Open a business bank account", target_day: 14, verification_question: "Have you opened a dedicated business bank account?" },
      ],
      prerequisite_outputs: null,
    },
  },
  3: {"id":3,"name":"Professional Presence","track":"A","access_tier":"tranche_1","applicable_sectors":null,"prerequisite_module":null,"area":"Market Presence","trigger_phase":"Days 1–14","estimated_minutes":5,"output_type":"presence_action_plan","description":"Domain, email, LinkedIn positioning, and the website question — with a direct opinion on what matters in your first 90 days.","what_you_get":"Specific recommendations on domain, email, LinkedIn positioning, and whether you need a website at this stage.","questions":[{"id":"trading_name","text":"What name are you planning to trade under?","type":"choice","options":["My own name","A business name I've chosen","Undecided"]},{"id":"domain_registered","text":"Do you already have a domain registered in your name or trading name?","type":"choice","options":["Yes","No"]},{"id":"linkedin_status","text":"What does your LinkedIn headline currently say?","type":"choice","options":["Still shows my current or previous employer role","Already updated to reflect independent work","I don't have a LinkedIn profile"]},{"id":"website_status","text":"Do you already have a professional website?","type":"choice","options":["Yes, live","No","In progress"]}],"output_structure":{"trading_name_recommendation":"Own name vs. business name recommendation with rationale","day_1_actions":"Domain and professional email — specific instructions and tool recommendations","week_1_actions":"LinkedIn rewrite framework — 5 questions to answer for headline, about, and services sections. Pre-draft headline from archetype + model + Q6.","month_1_3_optional":"One-page website if wanted — recommended tool, what the page needs to say","not_now":"What to deprioritise — full brand identity, logo, multi-page site","note":"Your first clients will almost certainly come from people who already know you — not from inbound web search. A professional email and updated LinkedIn profile are more valuable than a website in the first 90 days."},
    module_addendum: {
      module_decision_frame: "User has chosen a trading name approach (Q1: own name / business name / undecided), has or has not registered a domain (Q2), has a LinkedIn status (Q3, still showing previous employer is the common starting point), and has or has not built a website (Q4). The decision is what to build in the first 90 days. Strong opinion to convey: in the first 90 days an updated LinkedIn profile + a professional email on your own domain + a registered domain beat a multi-page website. Most first clients come from the existing network, not inbound web search.",
      module_specific_knowledge: `Trading name decision: own name fits advisory and consulting work where personal brand matters and clients buy the individual. Business name fits productised offerings, services you plan to scale beyond yourself, or sectors where a business name signals legitimacy (e.g. some FS procurement teams prefer a corporate vendor name). Switching from own name to a business name later is straightforward; the reverse is harder once a business identity is established.

Domain registration: register the domain in your chosen trading name whether or not you build a site this year. Reputable registrars: Namecheap, Cloudflare Registrar, 123-reg, GoDaddy. Cost £8-£15/year for a .com or .co.uk. Register the variants you care about defensively (.com, .co.uk, .uk), same registrar, same renewal date.

Professional email: switching from a gmail.com or hotmail.com address to youremail@yourdomain.com is the single biggest credibility upgrade in the first 90 days. Options: Google Workspace (£5-£12/user/month, gmail-quality interface), Microsoft 365 Business (£5-£10/user/month, Outlook + Office), Fastmail (£3-£8/month, privacy-focused), Proton Mail (£4-£10/month, encrypted). Setup involves pointing your domain's MX records at the provider, the provider walks you through it.

LinkedIn rewrite framework. Headline (220 chars): what you do + for whom + outcome. Example: "Fractional compliance advisor to UK FS firms, pre-trade risk reviews and SMCR readiness". Avoid generic titles like "Consultant" or "Advisor" with no specificity. About section first three lines are visible above the fold without expansion; lead with the specific problem you solve. Featured section: pin one or two pieces of work or thought leadership if available. Services section: list 2-4 named services with brief descriptions. Open to Work / Open to Providing Services: turn on Open to Providing Services with your specific service categories.

Website decision: skip for the first 90 days unless a specific client requires it for procurement. If you do need one quickly, single-page Carrd (£19/year) or Cargo (£15/month) builds in 4 hours. Squarespace and Webflow are heavier options for when you have actual content. Wordpress fits if you plan to blog regularly.

What to deprioritise actively in the first 90 days: full brand identity work with a designer, logo design, multi-page corporate website, business cards (rarely useful in modern B2B), corporate stationery. These are real costs that don't move conversion in the first 90 days for most independent consultants. Revisit at Month 6-12 once income is established.`,
      curated_caveat_base: "Domain registrar and email provider pricing changes periodically. Compare 2-3 options before buying. LinkedIn product changes occasionally; the headline character limits and section names above were accurate as of [DATE]; verify on LinkedIn directly before rewriting.",
      curated_caveat_verified_date: "2026-05-25",
      commitments_template: [
        { action_hint: "Register the domain in your trading name", target_day: 3, verification_question: "Have you registered your domain?" },
        { action_hint: "Update LinkedIn headline and about section", target_day: 7, verification_question: "Have you updated your LinkedIn profile to reflect independent work?" },
        { action_hint: "Set up professional email on your domain", target_day: 14, verification_question: "Are you now sending email from your professional address?" },
      ],
      prerequisite_outputs: null,
    },
  },
  4: {"id":4,"name":"Tax Basics & Self Assessment","track":"B","access_tier":"subscription","applicable_sectors":null,"prerequisite_module":1,"area":"Financial Management","trigger_phase":"Days 8–14","estimated_minutes":8,"output_type":"obligations_summary","description":"Your tax obligations, key dates, and the Year 1 traps that catch most new independents.","what_you_get":"A clear picture of your Year 1 tax bill, key dates, payment on account explained, and what to set aside monthly.","questions":[{"id":"structure","text":"Which structure are you operating under?","type":"choice","options":["Sole trader","Limited company","Umbrella company","Not decided yet"],"pre_populate_from":"module_1_output.recommendation"},{"id":"employment_status","text":"Are you currently employed as well as doing independent work?","type":"choice","options":["Yes — employed plus independent work","No — fully independent now"]},{"id":"expected_profit_year1","text":"What is your approximate expected profit (income minus deductible costs) in Year 1?","type":"choice","options":["Under £12,570 (below personal allowance)","£12,570–£50,270","£50,270–£125,140","Over £125,140"]},{"id":"accountant_engaged","text":"Do you have an accountant or plan to engage one?","type":"choice","options":["Yes, already have one","Considering it","No — planning to self-file"]}],"output_structure":{"applicable_taxes":"Specific taxes and NI obligations for their structure and employment status","key_dates":"Critical deadlines — registration, payment on account, filing — specific to their Year 1 situation","effective_rate_estimate":"Rough effective tax rate at their income band","year_1_traps":"The payment on account shock, late registration penalties, and missed allowances most common in Year 1","missed_deductions":"3 most relevant deductions for their business model","accountant_guidance":"Whether to engage an accountant and what to ask them for at this stage","caveat":"This is a summary for orientation — not a substitute for professional tax advice. Confirm with an accountant before filing, particularly in Year 1."},
    module_addendum: {
      module_decision_frame: "User is operating under a chosen structure (Q1 pre-populated from Module 1), may have parallel employment income (Q2), has an expected Year 1 profit band (Q3), and may have or be considering an accountant (Q4). Produce applicable taxes for their structure + employment status, key dates, effective rate estimate at their profit band, the Year 1 traps (payment on account shock, late registration penalty, missed allowances), the 3 most relevant missed deductions for their business model, and accountant guidance. The decisive Year 1 trap is payment on account: the first January after the first tax year, HMRC charges roughly 150% of the year's bill (the balancing payment plus a 50% advance on the next year).",
      module_specific_knowledge: `UK 2026/27 Income Tax bands (England, Wales, Northern Ireland): Personal Allowance £12,570 (tapered by £1 for every £2 of income above £100,000; fully gone at £125,140); Basic rate 20% from £12,571 to £50,270; Higher rate 40% from £50,271 to £125,140; Additional rate 45% above £125,140. Scottish bands differ; user should check gov.uk/scottish-income-tax if Scottish resident.

National Insurance for sole traders 2026/27: Class 2 is abolished from 2024-25 for those above the Small Profits Threshold of £6,725 (those below can pay voluntarily for state pension qualifying years). Class 4 rates: 6% on profits from £12,570 to £50,270; 2% above £50,270. Class 4 NI is paid alongside Income Tax through Self Assessment.

National Insurance for limited company directors: Employer NI applies to director salary above the Secondary Threshold (£9,100 for 2026/27 typically); 13.8% rate. Employee NI on director salary above the Primary Threshold (£12,570); 8% rate. Dividends are NI-free. The salary-dividend optimisation typically pays the director a salary at or near the personal allowance and the rest as dividends.

Corporation Tax for limited companies 2026/27: 19% on profits up to £50,000 (small profits rate); 25% on profits above £250,000 (main rate); marginal relief between, giving an effective marginal rate of approximately 26.5% on profit between £50k and £250k.

Dividend tax: £500 tax-free Dividend Allowance for 2026/27. Above the allowance: 8.75% basic rate, 33.75% higher rate, 39.35% additional rate. Dividends count towards the tax band thresholds (so a £40,000 dividend on top of a £12,570 salary uses up the basic rate band).

Key dates a sole trader cannot miss: 6 April tax year start; 5 April tax year end; 5 October following the tax year is the Self Assessment registration deadline (£100+ penalty for late); 31 January is the online filing deadline and payment due date for the prior tax year, AND the first payment on account deadline for the current year if prior tax bill exceeded £1,000; 31 July is the second payment on account deadline.

The payment on account trap. First Self Assessment in late January demands: (1) the balancing payment for the year just ended; (2) a payment on account equal to 50% of that year's bill, as an advance against the current year. So if Year 1 tax is £8,000, the January demand is £12,000. Sets up the cash crunch. Module 1's reference layer covers the tax reserve habit that prevents this.

Top three commonly missed deductions for sole trader advisors and consultants: (1) use of home as office, either flat-rate (£10-£26/month depending on hours worked from home, per HMRC simplified expenses) or proportional (utilities × business use percentage); (2) professional subscriptions on HMRC's approved list (e.g. CIPD, ICAEW, CFA membership); (3) software subscriptions wholly and exclusively for business (Xero, Notion, Adobe). Mileage is allowable at HMRC's approved rates (45p/mile first 10,000 miles, 25p above) for journeys to clients but NOT for commute to a regular workplace.

Accountant Year 1 economics: a one-off Year 1 consultation typically £150-£250, worth it for almost everyone in Year 1 specifically. Ongoing sole trader Self Assessment service £300-£600 annually. Ongoing limited company retainer (accounts, CT600, payroll, director SA) £900-£1,500 annually. See Module 1 reference items for the questions to ask an accountant before engaging.`,
      curated_caveat_base: "Tax rates, thresholds, and reliefs change at Budget and Autumn Statement. Verify current rates at gov.uk/income-tax-rates and gov.uk/self-employed-national-insurance-rates before relying on the figures above. For Year 1 specifically, a one-hour consultation with a UK-qualified accountant (typically \u00a3150-\u00a3250) is usually money well spent. Verified [DATE].",
      curated_caveat_verified_date: "2026-05-25",
      commitments_template: [
        { action_hint: "Confirm Self Assessment or Corporation Tax registration is complete", target_day: 7, verification_question: "Have you confirmed registration with HMRC for your structure?" },
        { action_hint: "Set aside tax reserve from each invoice", target_day: 14, verification_question: "Are you moving a tax reserve percentage from each invoice into a separate account?" },
        { action_hint: "Decide on accountant engagement for Year 1", target_day: 30, verification_question: "Have you engaged an accountant or decided to self-file Year 1?" },
      ],
      prerequisite_outputs: null,
    },
  },
  5: {"id":5,"name":"VAT","track":"B","access_tier":"subscription","applicable_sectors":null,"prerequisite_module":1,"area":"Financial Management","trigger_phase":"Days 8–14","estimated_minutes":5,"output_type":"vat_decision_guide","description":"Whether to register for VAT, and if so which scheme — the decision most consultants either ignore or get wrong.","what_you_get":"A VAT registration decision with rationale, the right scheme for your situation, and the cash flow implications.","questions":[{"id":"expected_turnover","text":"What is your expected annual turnover in Year 1?","type":"choice","options":["Under £30,000","£30,000–£60,000","£60,000–£90,000","Over £90,000"]},{"id":"client_type","text":"Are your target clients primarily VAT-registered businesses, or a mix including individuals and small unregistered businesses?","type":"choice","options":["Primarily VAT-registered businesses (corporate, public sector)","Mix — including individuals and small businesses","Primarily individuals and very small businesses"]},{"id":"input_costs","text":"Do you expect to have significant business costs you'd want to reclaim VAT on — equipment, software subscriptions, subcontractors?","type":"choice","options":["Yes, meaningful costs","Some, but not significant","No — very low cost base"]}],"decision_logic":{"mandatory_threshold":"£90,000 rolling 12-month turnover — register within 30 days of exceeding","voluntary_register_if":["primarily B2B clients who can reclaim VAT","meaningful input costs to reclaim"],"do_not_register_if":["primarily individual or small business clients","income well below threshold","adds cost without benefit"],"flat_rate_scheme":"Often beneficial for service businesses with low input costs — charge 20% keep the difference between that and the flat rate (14.5% for management consultancy)","cash_accounting":"Recommended if invoicing in arrears — pay VAT when received not when invoiced"},"output_structure":{"vat_decision":"Register now | Register when approaching threshold | Voluntary registration recommended | Not recommended","scheme_recommendation":"Standard | Flat Rate (with rate) | Cash Accounting | N/A","rationale":"Specific reasons from their answers","action_if_registering":"What to do next","caveat":"VAT rules and thresholds can change. Always verify the current threshold and rates at gov.uk/vat before registering."},
    module_addendum: {
      module_decision_frame: "User has expected annual turnover (Q1), client type mix (Q2, primarily B2B or includes individuals/small unregistered businesses), and a sense of input costs (Q3). The decision is whether to register for VAT now, when approaching threshold, or not at all; and if registering, which scheme. Mandatory threshold is \u00a390,000 rolling 12-month turnover for 2026/27. Below that, voluntary registration trades off cleanly: B2B-heavy means clients reclaim so charging VAT does not affect their economics, and you reclaim input VAT; B2C-heavy means you effectively raise your prices by 20%, eating margin or losing custom. Flat Rate Scheme is often the right answer for service businesses with low input costs.",
      module_specific_knowledge: `Mandatory VAT registration: triggered when rolling 12-month VAT-able turnover exceeds £90,000 (UK 2026/27 threshold, held since April 2024). Note this is a rolling 12-month measure, not a calendar year or tax year measure, you can hit it mid-year if a single large invoice tips you over. Once triggered, register within 30 days of the end of the month you exceeded; effective date is the first day of the second month after triggering. Late registration penalty scales with the delay and the VAT you should have charged.

Voluntary registration economics. If your clients are primarily VAT-registered businesses (B2B), they reclaim the VAT you charge, so adding 20% to invoices is neutral for them, and you get to reclaim VAT on your inputs (software, training, equipment). Net positive almost always. If your clients are primarily individuals or small unregistered businesses (B2C, sub-£90k businesses), charging 20% effectively raises your price; either your client absorbs and your prices look 20% higher, or you absorb and your margin drops. Net negative usually below threshold.

The schemes. Standard scheme: charge 20% VAT on outputs; reclaim VAT on inputs; quarterly returns. Most flexible, most paperwork.

Flat Rate Scheme (FRS): charge 20% VAT on outputs but pay HMRC a flat percentage of gross turnover (sector-specific). Keep the difference. For 2026/27 the flat rates include: 14.5% Management Consultancy, 14.5% Computer and IT consultancy, 12% IT consulting (legacy band), 11% Architect/Civil/Structural Engineering, 11% Lawyer or Legal Services, 12% Advertising, 12% Accountancy or book-keeping. First-year discount: 1% reduction in your applicable rate for the first 12 months of VAT registration. FRS works best when input VAT to reclaim is low (the FRS is structured so you give up the right to reclaim input VAT on most things, exception: single capital assets over £2,000 including VAT). The Limited Cost Trader test: if input goods are less than 2% of turnover OR less than £1,000 annually, you pay 16.5% regardless of sector, making FRS unattractive. Most pure-advisory consultants are limited cost traders.

Cash Accounting Scheme: pay VAT to HMRC when you actually receive the cash, not when you raise the invoice. Reclaim input VAT only when you pay supplier invoices. Compatible with Standard scheme; not with Flat Rate. Useful if your invoicing is in arrears or you have slow-paying clients.

Annual Accounting Scheme: one annual VAT return plus monthly or quarterly interim payments based on prior year's bill. Reduces compliance overhead. Compatible with cash accounting.

Making Tax Digital (MTD): VAT-registered businesses must keep digital records and file returns through compatible software. Xero (£15-£59/month), FreeAgent (£19-£29/month, free with NatWest/RBS/Mettle business banking), QuickBooks (£14-£59/month), Sage (£12-£40/month) all MTD-compliant. Spreadsheet-only filing requires bridging software.`,
      curated_caveat_base: "VAT thresholds and Flat Rate percentages change at Budget and Autumn Statement. The \u00a390,000 threshold has been held since April 2024; confirm current threshold and FRS rates at gov.uk/vat-rates and gov.uk/vat-flat-rate-scheme before acting. Verified [DATE].",
      curated_caveat_verified_date: "2026-05-25",
      commitments_template: [
        { action_hint: "Confirm VAT decision and document rationale", target_day: 14, verification_question: "Have you decided whether to register for VAT now, when approaching threshold, or not at all?" },
        { action_hint: "Register for VAT if applicable", target_day: 30, verification_question: "If you decided to register, is the registration submitted?" },
      ],
      prerequisite_outputs: null,
    },
  },
  6: {"id":6,"name":"IR35 Risk & Protection","track":"B","access_tier":"subscription","applicable_sectors":null,"prerequisite_module":1,"area":"Compliance","trigger_phase":"Phase 2 — first outreach","estimated_minutes":8,"output_type":"risk_profile_with_protection_steps","description":"Your IR35 risk profile and practical steps to protect your position before your first client engagement.","what_you_get":"Your IR35 risk assessment, the three tests explained in plain English, and specific contract and working practice protections.","questions":[{"id":"operating_structure","text":"Are you operating as a limited company?","type":"choice","options":["Yes — limited company","No — sole trader or umbrella"],"pre_populate_from":"module_1_output.recommendation","skip_if_sole_trader":true},{"id":"client_pattern","text":"Will most of your work be for a single client for an extended period, or spread across multiple clients?","type":"choice","options":["Primarily one client at a time","Multiple clients simultaneously","Mix — depends on the engagement"]},{"id":"client_control","text":"Does the client control how you work — your hours, location, and methods — or only what you deliver?","type":"choice","options":["They control how I work (hours, location, method)","They specify deliverables — I control how I work","Mix of both"]},{"id":"substitution_right","text":"Do you have the right to send a substitute to do the work in your place?","type":"choice","options":["Yes, contractually","No","Not yet agreed / unsure"]},{"id":"client_size","text":"Are your target clients primarily large organisations (over 50 employees), or predominantly smaller businesses?","type":"choice","options":["Mostly large — over 50 employees, significant turnover","Mix","Mostly small — under 50 employees"]}],"decision_logic":{"low_risk":["multiple clients","control over method","substitution right","small clients"],"medium_risk":["occasional single dominant client","partial control","no substitution clause"],"high_risk":["single dominant client","client controls hours/location/method","no substitution right","large client sets status"]},"output_structure":{"risk_profile":"Low | Medium | High","risk_factors":"Specific factors from their situation","protection_steps":"Practical contract and working practice steps","cest_guidance":"Whether to use HMRC CEST and how to interpret it","specialist_referral":"When a specialist review is warranted","caveat":"IR35 is complex and HMRC can investigate historic determinations. If you are operating in a high-risk pattern, a one-off review with an IR35 specialist (typically £200–400) is a worthwhile investment."},
    module_addendum: {
      module_decision_frame: "User operating as a limited company (Q1, pre-populated from Module 1; if sole trader the module is skipped because IR35 does not apply) with a client pattern (Q2), client control profile (Q3), substitution clause status (Q4), and client size (Q5). Compute IR35 risk profile (low/medium/high) against the three statutory tests (mutuality of obligation, control, substitution) plus client-size context (since April 2021 medium-large clients determine status; small clients leave the contractor to determine). Produce contract and working-practice protections specific to their risk band. For high-risk cases recommend a specialist IR35 review.",
      module_specific_knowledge: `IR35 (the Intermediaries Legislation, also known as the off-payroll working rules) determines whether HMRC treats a limited company contract as 'disguised employment'. If inside IR35, the engagement is taxed as if it were employment (PAYE income tax + NI), and the limited company structure's tax advantage evaporates for that contract. If outside IR35, the Ltd retains its tax efficiency.

The three statutory tests, established in Ready Mixed Concrete v Minister of Pensions (1968) and refined by subsequent case law:

Mutuality of obligation (MOO): is the client obliged to offer work, and the contractor obliged to accept? Employment requires ongoing mutual obligation. Independent engagement is typically piece-by-piece with no obligation either way after the current piece ends.

Control: does the client control how, when, and where the work is done? Employees are subject to control on method. Independents are typically engaged for a deliverable and control their own method.

Substitution: can the contractor genuinely send a substitute to do the work in their place? A real substitution right (not 'with the client's approval, not to be unreasonably withheld', too weak) indicates independence. A personal-service-only engagement leans towards employment.

Plus context factors: provides own equipment, takes financial risk, has multiple clients, has a business of their own (insurance, website, business bank account).

Status determination responsibility (since April 2021 Off-Payroll Working reforms): For medium-large private sector clients (meets 2 of 3: more than 50 employees; turnover above £10.2m; balance sheet above £5.1m) AND all public sector clients, the CLIENT determines IR35 status and issues a Status Determination Statement (SDS). The fee-payer (often the client, sometimes a recruitment agency in the chain) operates payroll. For small private clients (below all 3 thresholds), the contractor determines.

CEST tool (Check Employment Status for Tax): HMRC's online tool at tax.service.gov.uk/check-employment-status-for-tax. Not legally binding but accepted by HMRC if used honestly and the facts match. Results often 'Undetermined' for advisory engagements; run it and save the result as paper trail regardless.

Contract protections for outside-IR35 positioning: genuine and exercisable substitution clause; right of refusal (no obligation to accept future work); fee per deliverable not per day where possible; ownership of own equipment; multiple clients in concurrent engagements.

Working practice protections: do not appear in client org chart or directory; do not attend client team meetings as a team member; do not take direction on working hours or location; bill against a defined scope rather than time on the client's clock; use your own equipment where practical; avoid 'extras' beyond the scope without a change request.

Specialist IR35 review: contract + working practices review costs £200-£400 typically; worthwhile for any engagement above £20,000 of expected revenue or any engagement with a medium-large client that has not issued an SDS. Specialists include QDOS, Bauer & Cottrell, Markel Tax, and several boutique IR35-focused consultancies. Some PI insurers include IR35 cover that pays defence costs in an HMRC investigation.

If a client issues an inside-IR35 SDS for a contract you believe is outside: you have 45 days to appeal in writing; the client must respond within 45 days. You can accept and continue (taxed as employment with no employment rights); switch to umbrella for that engagement (cleaner administratively); decline the work; or escalate to HMRC's enforcement team if you believe the determination is wrong.`,
      curated_caveat_base: "IR35 case law evolves and HMRC investigates historic determinations up to 6 years back (and 20 years in cases of deliberate non-disclosure). The framework above is structured guidance not a legal status determination. For any engagement you are meaningfully uncertain about, a one-off review with an IR35 specialist (typically \u00a3200-\u00a3400) is the right next step. Verified [DATE].",
      curated_caveat_verified_date: "2026-05-25",
      commitments_template: [
        { action_hint: "Run CEST on your typical engagement profile and save the result", target_day: 7, verification_question: "Have you run the HMRC CEST tool and saved the result?" },
        { action_hint: "Add a genuine substitution clause to your standard contract", target_day: 14, verification_question: "Does your standard contract include a substitution clause you would actually be willing to exercise?" },
        { action_hint: "Decide your specialist-review threshold", target_day: 14, verification_question: "Have you decided at what engagement value or risk level you will commission a specialist IR35 review?" },
      ],
      prerequisite_outputs: null,
    },
  },
  7: {"id":7,"name":"Contracts & Statements of Work","track":"B","access_tier":"subscription","applicable_sectors":null,"prerequisite_module":null,"area":"Compliance","trigger_phase":"Phase 2 — first outreach","estimated_minutes":8,"output_type":"contract_checklist","description":"The contractual protection you need before your first engagement — clause by clause, calibrated to your work type and typical engagement value.","what_you_get":"The key clauses to include, the ones to push back on, and a practical SOW template structure.","questions":[{"id":"work_type_detail","text":"What type of work will you primarily be doing?","type":"choice","options":["Advisory and consulting","Project delivery and implementation","Interim management","Training and facilitation","Mix of the above"],"pre_populate_from":"q4_work_type"},{"id":"ip_creation","text":"Will you be creating intellectual property for clients — reports, methodologies, frameworks, written materials, software?","type":"choice","options":["Yes, regularly","Sometimes","No — primarily advisory"]},{"id":"contract_provider","text":"Will you be providing your own contract, or will clients typically send theirs?","type":"choice","options":["I'll provide my own","Clients will send theirs","Mix — depends on the client"]},{"id":"typical_engagement_value","text":"What is the likely value of a typical engagement?","type":"choice","options":["Under £5,000","£5,000–£20,000","Over £20,000"]},{"id":"payment_terms_preference","text":"What payment terms are you planning to use?","type":"choice","options":["30 days from invoice","50% upfront, balance on completion","Monthly retainer","Milestone-based","Not yet decided"]}],"output_structure":{"essential_clauses":"Checklist of key contract clauses for their work type — scope, IP ownership, payment terms, liability cap, termination, confidentiality — with plain-English brief on each","scope_creep_protection":"How to write scope definitions and change request clauses for their work type","payment_protection":"Recommended payment terms, late payment clause, deposit structure","template_vs_lawyer":"Guidance on when a template is sufficient vs. when to get a commercial review","sow_guidance":"Whether a standalone Statement of Work is needed alongside the master contract","caveat":"This is a structured guide, not legal advice. For high-value engagements or heavily one-sided client contracts, a one-hour review with a commercial solicitor (typically £200–400) is worth it."},
    module_addendum: {
      module_decision_frame: "User has a work type (Q1 pre-populated from main questionnaire), IP creation pattern (Q2), contract source preference (Q3, own contract vs client contract vs mix), typical engagement value (Q4), and payment terms preference (Q5). Produce a contract checklist with essential clauses tailored to their work type, scope-creep protections, payment-protection guidance, and a clear template-vs-solicitor decision. For high-value engagements (above ~\u00a320,000) or heavily one-sided client contracts, recommend a one-hour commercial solicitor review.",
      module_specific_knowledge: `Essential clauses for any service contract between professionals. Scope of work: defined deliverables, not open-ended 'consultancy services'. Payment terms: amount, schedule, currency, late payment provisions. Intellectual property: who owns what the contractor produces, what pre-existing IP the contractor retains. Liability cap: limit on the contractor's financial exposure (industry norm: fees paid in the 12 months preceding the claim). Indemnities: what each party indemnifies the other for. Confidentiality: what is confidential, for how long, what carve-outs (e.g. publicly available, independently developed). Termination: notice periods, payment on early termination. Governing law and jurisdiction: usually England and Wales for UK independents.

IP ownership trade-offs. Client work product (the specific deliverables) typically vests in the client on payment under a 'work for hire' or assignment clause. Pre-existing methodologies, frameworks, templates, and tools the contractor brings to the engagement should be explicitly carved out as the contractor's IP, with the client granted a perpetual licence to use them as part of the deliverable. Reusable frameworks the contractor develops during the engagement (with significant new IP) need explicit retained-rights language or they default to the client.

Liability cap. Standard market is 'fees paid in the 12 months preceding the claim'. Never accept uncapped liability for an advisory engagement: a single claim could exceed your insurance and personal assets. Standard carve-outs to the cap (which remain uncapped) are: gross negligence, wilful misconduct, IP infringement, breach of confidentiality. Some clients ask for a cap of 'fees paid under this contract' (lower) or '£1 million' (higher); negotiate to the 12-month-fees standard.

Payment terms in UK B2B. Net 30 is the default. Industry-by-industry deviations: construction and creative agencies often pay net 60-90; FS and large corporate clients often net 30-45 but pay closer to 45-60; public sector contractually obligated to pay within 30 days (Public Contracts Regulations 2015). Statutory protection for late payment: the Late Payment of Commercial Debts (Interest) Act 1998 entitles you to charge 8% over the Bank of England base rate (so currently around 13%) plus a fixed late-payment fee of £40, £70, or £100 per overdue invoice depending on debt size. Including this clause in your standard terms makes enforcement straightforward.

Scope-creep protection. Define scope as deliverables rather than 'consulting services'. Include a change request process: any change in writing, priced before work begins, signed off by named client side approver. Set a buffer fee (e.g. 'time beyond defined scope billed at £X/day on prior written agreement') so unexpected requests have a clear price.

Statement of Work (SOW). Use a standalone SOW for each engagement under a master MSA (Master Services Agreement). The MSA contains the legal framework (IP, liability, governing law, payment terms); the SOW contains the specific engagement (scope, deliverables, fees, dates, named client contact). Lets you re-engage the same client without re-negotiating the MSA each time.

Templates vs solicitor review. Template (Law Depot, Rocket Lawyer, Crunch Insurance, free templates from professional bodies) is fine for: engagements under £20,000 of expected revenue; both parties are professional businesses; the work pattern is straightforward (advisory hours, project deliverables); the client has not sent their own heavily-detailed contract. Solicitor review (£200-£400 for a one-hour commercial review) is warranted for: any engagement above ~£20,000; any contract the client has sent that runs over 15 pages; contracts containing unusual IP, indemnity, exclusivity, or non-compete clauses; engagements with regulated sectors (FCA, healthcare) where regulatory liability flows through the contract.

What to push back on in client-sent contracts. Uncapped liability (industry norm is fees paid in 12 months). Broad IP assignment of pre-existing materials (should be carved out as retained IP with licence). Asymmetric indemnities (should be mutual). Exclusivity clauses (you should remain free to work with non-competing clients). Post-engagement non-compete clauses (rarely enforceable for independents and harmful to your portfolio). Onerous warranty language ('the deliverables will be free of errors and fit for purpose', unrealistic for advisory work; soften to 'performed with reasonable professional skill and care').`,
      curated_caveat_base: "Contract law and standard market terms evolve. The clauses above are structured guidance, not legal advice. For high-value engagements (above ~\u00a320,000), heavily one-sided client contracts, or any contract with unusual IP, indemnity, or liability provisions, a one-hour commercial solicitor review (typically \u00a3200-\u00a3400) is worth it. Verified [DATE].",
      curated_caveat_verified_date: "2026-05-25",
      commitments_template: [
        { action_hint: "Decide template or solicitor route for your first contract", target_day: 14, verification_question: "Have you chosen your contract approach for the first engagement?" },
        { action_hint: "Draft your standard SOW template", target_day: 30, verification_question: "Have you drafted a standard SOW template you can reuse?" },
        { action_hint: "Identify a commercial solicitor for review threshold", target_day: 30, verification_question: "Have you identified a commercial solicitor you would use for engagements above your review threshold?" },
      ],
      prerequisite_outputs: null,
    },
  },
  8: {"id":8,"name":"Data Protection & GDPR","track":"B","access_tier":"subscription","applicable_sectors":null,"prerequisite_module":null,"area":"Compliance","trigger_phase":"Phase 2 — first outreach","estimated_minutes":6,"output_type":"data_protection_action_plan","description":"Whether you need to register with the ICO, what a data processing agreement actually requires, and your practical data handling obligations.","what_you_get":"A clear answer on ICO registration requirement, what a DPA needs to include, and how to respond if a client requests one.","questions":[{"id":"personal_data_handling","text":"In your work, do you handle personal data about individuals — employees, customers, patients, clients?","type":"choice","options":["Yes, regularly — it's core to the work","Sometimes — depends on the project","Rarely or never — I work with anonymised or business data"]},{"id":"data_controller_or_processor","text":"In your typical engagement, are you determining how and why personal data is used (controller), or just processing it on the client's instructions (processor)?","type":"choice","options":["I determine how data is used — I'm acting as a controller","I process data under the client's direction — I'm acting as a processor","Not sure — it varies"]},{"id":"client_sends_dpa","text":"Have any of your target clients or prospects asked you to sign a Data Processing Agreement?","type":"choice","options":["Yes","Not yet, but I expect them to","No — unlikely given my clients"]},{"id":"ico_registered","text":"Are you already registered with the ICO?","type":"choice","options":["Yes","No","Unsure what that is"],"pre_populate_from":"module_2_output.ico_registration"}],"decision_logic":{"ico_required":["handles personal data in the course of work","data controller role","access to employee/customer/patient records"],"dpa_required":["client asks for DPA","processor role with sensitive data","healthcare, HR, financial services, recruitment sectors"],"minimal_obligations":["works entirely with anonymised or aggregated data","strategic advisory with no data access"]},"output_structure":{"ico_registration_decision":"Required / Not required — with rationale and registration link (ico.org.uk, £40–52/year, 10 minutes)","dpa_guidance":"What a DPA needs to cover, who typically initiates it, and what to watch for in client-sent DPAs","practical_data_obligations":"Data retention, breach notification, privacy notice requirements specific to their work type","sector_specific_flags":"Any sector-specific data obligations (e.g. healthcare, financial services) surfaced from Q11","caveat":"GDPR compliance is the legal responsibility of each individual or organisation. If your work involves sensitive personal data or healthcare records, confirm your obligations with a data protection specialist."},
    module_addendum: {
      module_decision_frame: "User handles personal data in their work (Q1, yes/sometimes/no), acts as controller or processor (Q2), may have been asked for a DPA (Q3, yes/expected/no), and may already be ICO-registered (Q4, pre-populated from Module 2). Produce ICO registration decision with rationale and registration link, DPA guidance (what it covers, who initiates, what to watch for in client-sent versions), practical data obligations (retention, breach notification, privacy notice), and sector-specific flags surfaced from Q11. For sensitive-data sectors (healthcare, financial services with personal records, recruitment, HR), recommend a data protection specialist.",
      module_specific_knowledge: `ICO registration. Legal requirement for any data controller processing personal data in the course of business under the Data Protection (Charges and Information) Regulations 2018. Fees for 2026/27: tier 1 (micro) £40, tier 2 (SME) £60, tier 3 (large) £2,900. Most independent consultants fall in tier 1 or tier 2. Register at ico.org.uk/registration. The process takes about 10 minutes online; you receive immediate confirmation and an annual renewal reminder. Non-registration when required is itself an offence; ICO can prosecute.

Controller vs processor. A controller decides why and how personal data is used. A processor processes personal data on behalf of a controller, under the controller's instructions. An independent consultant working with a client's customer database under the client's direction is typically a processor. A consultant building and maintaining their own contact database for marketing is a controller of that database. The same engagement can have multiple roles, you might be a processor of the client's customer data and a controller of your own staff records and your own client contact list.

Lawful basis for processing. Six options under Article 6 of UK GDPR: consent, contract, legal obligation, vital interests, public task, legitimate interests. For B2B advisory engagements you are usually on 'contract' (necessary for the contract performance) or 'legitimate interests' (with a documented Legitimate Interests Assessment). Document which lawful basis you rely on for each category of processing.

Data Processing Agreement (DPA). Required by Article 28 of UK GDPR whenever a controller engages a processor. Must cover: subject matter and duration of processing; nature and purpose; type of personal data and categories of data subjects; obligations of the controller; obligations of the processor (specifically: act only on documented instructions, ensure personnel confidentiality, implement appropriate security, engage sub-processors only with controller approval, assist the controller with data subject rights, breach notification, deletion or return on termination, audit rights). Most large clients send their own DPA; smaller clients may ask you to provide one. Have a template ready.

Privacy notice. Required when you collect any personal data directly from data subjects. Must describe: identity and contact details of the controller (you), purposes of processing, lawful basis, recipients of the data, retention period, data subject rights (access, rectification, erasure, restriction, portability, objection), right to complain to the ICO. Common locations: a 'Privacy' page on your website; a paragraph in your engagement letter; a footer link in your professional email signature. Template generators include the ICO's own template service.

Data subject rights. Under UK GDPR data subjects have eight rights, including the right to access (a Subject Access Request must be answered within 1 month, can be extended by 2 months if complex), rectification, erasure ('right to be forgotten'), restriction, portability, objection, rights related to automated decision-making, and the right to be informed. As an independent, the practical preparation is: know where personal data is stored; be able to extract a single subject's data within the response window; have a deletion process you can execute on request.

Breach notification. Personal data breach must be reported to the ICO within 72 hours of becoming aware, if there is risk to data subjects. Affected individuals must be notified without undue delay if the breach is likely to result in high risk. Breaches include accidental disclosure, lost laptops with unencrypted client data, ransomware affecting personal data, and unauthorised access. Maintain a breach log even for breaches you do not report (the log itself is required).

Sub-processors. Any third party you use to process the personal data on the controller's behalf is a sub-processor. Common sub-processors for independent consultants: Google Workspace or Microsoft 365 (email, file storage), Dropbox, Notion, Zoom, accountants if they receive client data, transcription services, cloud hosting providers. The DPA must require controller approval before adding sub-processors; flow-down DPA terms must be in place with each sub-processor; maintain a sub-processor list.

Sector flags. Healthcare data (NHS, private health) is special category data under Article 9, additional conditions apply, often consent or explicit legal basis. Financial services data involving personal financial records carries both ICO and FCA considerations. Recruitment and HR involve significant subject access requests and right-to-be-forgotten activity. Children's data (under 13s, sometimes under 18s) has additional protections, explicit parental consent often required.`,
      curated_caveat_base: "UK GDPR compliance is the legal responsibility of each individual data controller and processor. The framework above is orientation, not specialist advice. For work involving special category personal data (healthcare, sexual orientation, political opinion, religious belief, biometric, genetic, racial or ethnic origin), criminal conviction data, or children's data, confirm your obligations with an ICO-experienced data protection specialist. Verified [DATE].",
      curated_caveat_verified_date: "2026-05-25",
      commitments_template: [
        { action_hint: "Register with the ICO if a controller", target_day: 14, verification_question: "Have you registered with the ICO, or confirmed registration is not required for your work?" },
        { action_hint: "Draft a basic privacy notice for your website or contact form", target_day: 30, verification_question: "Do you have a privacy notice ready to publish?" },
        { action_hint: "Save a DPA template for client-requested cases", target_day: 30, verification_question: "Do you have a DPA template ready when a client requests one?" },
      ],
      prerequisite_outputs: null,
    },
  },
  9: {"id":9,"name":"Insurance","track":"B","access_tier":"subscription","applicable_sectors":null,"prerequisite_module":null,"area":"Risk Management","trigger_phase":"Phase 2 — first outreach","estimated_minutes":8,"output_type":"personalised_insurance_brief","description":"What insurance you actually need — business and personal — before your first engagement, and what to deprioritise.","what_you_get":"The exact policies you need, recommended coverage levels, and what to tell your broker.","questions":[{"id":"works_at_client_premises","text":"Will you regularly work from client premises?","type":"choice","options":["Yes, frequently","Occasionally","No — primarily remote"]},{"id":"employs_staff","text":"Do you employ, or plan to employ, any staff or contractors?","type":"choice","options":["No — solo operator","Yes or planning to"]},{"id":"large_org_clients","text":"Do your target clients include large organisations that may have minimum insurance requirements as a contract condition?","type":"choice","options":["Yes — corporate or public sector clients likely","Mix","No — mostly smaller clients"]},{"id":"equipment_value","text":"What is the approximate replacement value of your working equipment (laptop, monitors, peripherals)?","type":"choice","options":["Under £1,500","£1,500–£3,000","Over £3,000"]},{"id":"lost_employee_benefits","text":"Did you have income protection insurance or life cover as an employee benefit that you are now losing?","type":"choice","options":["Yes — I had meaningful employee benefits","No or minimal","Unsure"]},{"id":"financial_dependents","text":"Do you have financial dependents — partner, children — who rely on your income?","type":"choice","options":["Yes","No"]}],"output_structure":{"business_insurance":{"must_have":"Professional Indemnity — recommended cover level and typical annual cost","should_consider":"Public Liability if relevant","legally_required_if":"Employers Liability conditions","optional":"Business equipment cover","broker_guidance":"Recommended broker types for their profile"},"personal_protection":{"income_protection":"Recommended deferred period, cover level, rough premium estimate","critical_illness_life":"Flagged if dependents present, otherwise optional review item","priority_guidance":"What to act on now vs. defer"},"caveat":"Insurance requirements and pricing vary significantly by specialism, claims history, and insurer. Get quotes from at least 2-3 brokers before purchasing.",
    module_addendum: {
      module_decision_frame: "User has a working pattern (Q1, frequency at client premises), employment plans (Q2, solo or planning to employ), client profile (Q3, large org clients with insurance requirements), equipment value (Q4), lost employee benefits signal (Q5), and dependent status (Q6). Produce a personalised insurance brief: business policies (PI must-have, PL if regularly at client premises, EL if employing), business equipment cover for high-value kit, personal protection (income protection, critical illness, life cover for dependents). Conservative on naming specific brokers per the Module 1 broker-shortlist pattern (selection criteria, not named brokers).",
      module_specific_knowledge: `Professional Indemnity (PI) insurance. Claims-made cover protecting against client claims of financial loss arising from your advice, services, or work product. Standard cover levels: £250,000 (sub-£50k revenue), £500,000 (£50k-£100k), £1,000,000 (£100k-£250k or large corporate clients), £2,000,000+ (institutional FS or large public sector clients). Premium £300-£1,500/year typical depending on revenue, work type, and claims history. Required by many corporate procurement teams as a precondition to engagement (often £1m minimum, sometimes £5m for FS or public sector). See Module 1's 'How to pick a PI broker' reference for selection criteria.

Public Liability (PL). Covers claims for bodily injury or property damage caused to third parties by your business activities. Most relevant if you regularly attend client premises (tripping a client, knocking over a screen, damaging client equipment). Standard limit £1m or £2m. Premium £100-£300/year. Often bundled with PI at a discount. Less relevant for primarily remote independents.

Employers' Liability (EL). Legally required under the Employers' Liability (Compulsory Insurance) Act 1969 if you employ anyone, including some family members on payroll and some contractor relationships that meet the definition. £5m minimum cover legally required (most policies provide £10m as standard). Premium £100-£300/year typical for a single director-only company; rises with headcount. Not required for a director-only company with no employees. Fines for not having it can be £2,500 per day.

Business equipment cover. Home contents insurance often excludes business equipment, or covers it only up to a low limit. Specific business equipment policies cover laptop, monitors, peripherals, mobile, tablets. Premium £40-£150/year for £3,000-£5,000 of kit. Some bundles include cover for client materials in your possession.

Cyber insurance. Increasingly relevant. Covers data breach response costs (notification, credit monitoring, ICO investigation), business interruption from cyber attack, ransomware payment (controversial, many insurers now exclude), legal defence costs. Premium £200-£500/year for an independent consultant. Separate from PI but increasingly bundled. Consider seriously if you process meaningful client personal data.

Income protection (IP). Insures a percentage of your pre-tax income (typically 50-65%) if you cannot work due to illness or injury. Critical parameters: deferred period (4 weeks, 3 months, 6 months, 12 months, longer deferred period means lower premium); definition of incapacity ('own occupation' is the strong definition; 'any occupation' is weaker and pays out only if you cannot do any job at all); waiver of premium during a claim; review period (rates re-rated at end of term vs guaranteed). Premium £40-£150/month typical for 30-50 year old non-smoker. Particularly important for solo earners with no employer sick pay; doubly so if you have dependents.

Critical illness (CI). Lump sum on diagnosis of a specified critical illness (cancer, heart attack, stroke being the big three, plus 30-60 other defined conditions depending on policy). £100,000-£500,000 cover typical. Useful if you have dependents or a mortgage; less critical if neither.

Life cover. Term assurance for dependent protection. £8-£25/month typical for £250,000 over 20-25 years for a non-smoker in their 30s-40s. Joint life or single life decision; level term or decreasing term. Critical if you have financial dependents.

PI broker selection (cross-applicable from Module 1). FS-specific experience matters; ask 'how many independent consultants on your book?'; Lloyd's market access; willingness to read your specific work into the wording; claims handling specifics. See Module 1 reference items.

What to deprioritise for a solo independent in Year 1: directors and officers (D&O) insurance (relevant when you take external investment or join boards), commercial property (n/a until you have premises), business interruption (specific triggers required), key person insurance (small business only), keyman cover for clients (very specialised), trade credit insurance.`,
      curated_caveat_base: "Insurance pricing varies significantly by sector, specialism, claims history, and individual broker. The figures above are indicative for a typical UK independent professional in 2026/27. Get quotes from at least 2-3 brokers before purchasing. For Professional Indemnity specifically, the policy wording and exclusions matter more than headline premium. Verified [DATE].",
      curated_caveat_verified_date: "2026-05-25",
      commitments_template: [
        { action_hint: "Get 3 PI insurance quotes from sector-experienced brokers", target_day: 14, verification_question: "Have you received at least 3 PI insurance quotes?" },
        { action_hint: "Bind a PI policy before your first client engagement", target_day: 30, verification_question: "Is your PI policy active?" },
        { action_hint: "Review income protection if losing employee cover", target_day: 30, verification_question: "Have you decided whether to take out income protection?" },
      ],
      prerequisite_outputs: null,
    },
  },
    module_addendum: {
      module_decision_frame: "User chose a structure in Module 1 (sole trader, limited company, or umbrella) and now needs the exact registration sequence with timeframes and costs. Produce a sequenced checklist tailored to the chosen structure plus an ICO registration determination based on Q4 work type and Q11 sector from the main questionnaire. Anchor urgency to Q1 trading_started: if the user has already done paid work, the HMRC Self Assessment clock is already running and registration is overdue rather than upcoming.",
      module_specific_knowledge: `Sole trader registration: complete at gov.uk/register-for-self-assessment using your National Insurance number. Takes about 15 minutes. HMRC posts a UTR (Unique Taxpayer Reference) within 10 working days. Registration deadline is 5 October following the tax year in which the first paid piece of work occurred. The initial late-registration penalty is £100 and rises with continued delay. No fee to register.

Limited company registration: incorporate at Companies House (find-and-update.company-information.service.gov.uk) for a £50 online fee. The incorporation completes within 24 hours typically. Corporation Tax registration is triggered automatically post-incorporation; HMRC sends an activation letter to the registered office within 14 days. Set up PAYE before paying yourself a salary (gov.uk/register-employer); even sole-director companies need PAYE if drawing salary above the Lower Earnings Limit. Annual filings are: company accounts due 9 months after year-end, confirmation statement annually (£34), corporation tax return CT600 12 months after year-end (payment 9 months and 1 day after).

Umbrella company onboarding: select an umbrella accredited by FCSA or Professional Passport (these are the two recognised industry bodies). Onboarding takes 1-3 days: right-to-work check, contract issuance, P45 transfer if applicable. Read the Key Information Document (KID) before signing, it discloses the umbrella margin, statutory deductions, and net take-home illustration. Umbrella margins vary £15-£35 per week typically.

ICO registration: legally required for any data controller processing personal data in the course of business under the Data Protection (Charges and Information) Regulations 2018. Fees: £40 (tier 1, micro), £60 (tier 2, SME), or £2,900 (tier 3, large), most independents fall in tier 1 or 2. Register at ico.org.uk/registration in about 10 minutes. Renewal is annual.

Business bank account: legally required for a limited company (the company is a separate legal entity and must not commingle funds). Strongly recommended for sole trader for clean records and audit trail. Traditional banks (HSBC, Barclays, Lloyds) take 2-4 weeks and may require an in-branch appointment. Neobanks (Starling, Tide, Monzo Business, Revolut Business) onboard within 1-3 days, often same-day. Starling and Tide are particularly common among independent consultants.

VAT and PAYE registrations are separate and triggered only when applicable (see Module 5 for VAT, Module 7 employer setup for PAYE).`,
      curated_caveat_base: "Registration deadlines, fees, and exact procedural steps occasionally change at Budget or Autumn Statement. Verify each step at gov.uk, companies-house.gov.uk, and ico.org.uk before acting. Verified [DATE].",
      curated_caveat_verified_date: "2026-05-25",
      commitments_template: [
        { action_hint: "Complete primary structure registration", target_day: 3, verification_question: "Have you registered with HMRC or Companies House for your chosen structure?" },
        { action_hint: "Register with ICO if applicable", target_day: 7, verification_question: "Have you registered with the ICO, or confirmed registration is not required for your work?" },
        { action_hint: "Open a business bank account", target_day: 14, verification_question: "Have you opened a dedicated business bank account?" },
      ],
      prerequisite_outputs: null,
    },
  },
};
