-- WP2 sub-PR A: Best-of-N candidate hook insights on reports.
--
-- Adds two columns to capture the N candidate hook insights generated by the
-- regenerate-hook-insight edge function (WP2), plus the index of the winning
-- candidate that got promoted to the canonical reports.hook_insight column.
--
-- Per `admin/wp2-best-of-n-design.md` v1.0 Q2 (signed off 2026-05-27):
-- candidate hooks live on `reports`, NOT `plans`, because the hook is a
-- report-stage output surfaced on the teaser page well before a plan row
-- exists.
--
-- Schema of `candidate_hook_insights` JSONB (no enforced shape, convention is):
--   [
--     {
--       "hook_insight": { "headline": "...", "paragraph": "...", "anchors_referenced": [...], "first_move_implied": "..." },
--       "judge_4_score": 0..5,
--       "judge_4_sub_scores": { "non_obvious": 0..2, "execution_critical": 0..2, "profile_specific": 0..1 },
--       "judge_4_must_not_be_matched": null | "<failure mode>",
--       "judge_4_justification": "...",
--       "prompt_hash": "<sha256 of prompt-2-hook-regenerator.md body at generation time>",
--       "generated_at": "2026-05-27T12:34:56Z"
--     },
--     ... up to N entries ...
--   ]
--
-- `hook_insight_winner_index` is the zero-based index into the array of the
-- candidate whose headline+paragraph got promoted to `reports.hook_insight`.
-- Null means either (a) row generated pre-WP2, or (b) regeneration ran but
-- the feature flag was off so the monolith's draft remained canonical.

ALTER TABLE public.reports
ADD COLUMN IF NOT EXISTS candidate_hook_insights JSONB,
ADD COLUMN IF NOT EXISTS hook_insight_winner_index INTEGER;

COMMENT ON COLUMN public.reports.candidate_hook_insights IS
'Array of {hook_insight, judge_4_score, judge_4_sub_scores, judge_4_must_not_be_matched, judge_4_justification, prompt_hash, generated_at} objects, in generation order. Set by regenerate-hook-insight edge function (WP2 sub-PR A). NULL on rows generated pre-WP2.';

COMMENT ON COLUMN public.reports.hook_insight_winner_index IS
'Zero-based index into candidate_hook_insights of the row promoted to the canonical hook_insight column. NULL if pre-WP2 OR if regeneration ran but the feature flag was off.';
